services:
  app:
    build:
      context: .
      target: build
    environment:
      - LD_KEY=$LD_KEY
    command: node --watch --no-warnings --loader ts-node/esm /app/src/index.ts
    network_mode: host

  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
    network_mode: host

volumes:
  redis:
